version: '3.3'
services:
  pg:
    container_name: UniversityApp
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
volumes:
  db_data: { }
